### ISSUE TITLE
Delete images in descriptions

### ISSUE THREAD

**Issue by alexlii1971** [rwkyyy/wc-product-images-delete#1]
Hello,

The images of product gallery can be deleted, but the images in description will still there.

Please check the screenshot at https://prnt.sc/UCAkXofD6n-f

So, could you please make it support deleting images in product description?

Thanks

**Comment by rwkyyy** [comment]
Hello @alexlii1971,

This is not something easy to solve, it would be needed to do multiple queries thus making the deleting process very slow and inefficient.
Normally you would add the images in description to the gallery itself.

I would recommend to DO A BACKUP first and then try using the [unattached images](https://wordpress.com/support/media/#unattached-files) functionality, natively to WordPress so you can clean the images that are left.

Hope it helps,
Have a nice week!
